version: '2.1'
services:
  bowser:
    environment:
      - TRAVIS=${TRAVIS}
      - TRAVIS_JOB_ID=${TRAVIS_JOB_ID}
      - TRAVIS_BRANCH=${TRAVIS_BRANCH}
      - TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
