version: '2.1'
services:
  bowser:
    environment:
      - CI=${CI}
      - TRAVIS=${TRAVIS}
      - TRAVIS_BRANCH=${TRAVIS_BRANCH}
      - TRAVIS_COMMIT=${TRAVIS_COMMIT}
      - TRAVIS_JOB_ID=${TRAVIS_JOB_ID}
      - TRAVIS_JOB_NUMBER=${TRAVIS_JOB_NUMBER}
      - TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
      - TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}
      - TRAVIS_TAG=${TRAVIS_TAG}
